[package]
name = "indigo-nursery"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
cola = { workspace = true }
ropey = { workspace = true }
serde = { workspace = true }
slotmap = { workspace = true }

[lints]
workspace = true
