[package]
name = "indigo_event"
version = "0.1.0"
authors = ["Evan Relf <evan@evanrelf.com>"]
license = "ISC"
edition = "2021"

[dependencies]
indigo_core = { path = "../indigo_core" }
tokio = { version = "1.18.0", features = ["full"] }
