[package]
name = "indigo_state"
version = "0.1.0"
authors = ["Evan Relf <evan@evanrelf.com>"]
license = "ISC"
edition = "2021"

[dependencies]

[[example]]
name = "type_map"

[[example]]
name = "custom_state"
