[package]
name = "indigo"
version = "0.1.0"
authors = ["Evan Relf <evan@evanrelf.com>"]
license = "ISC"
edition = "2021"

[[bin]]
name = "ind"
path = "src/main.rs"

[dependencies]
crossterm = "0.22.1"
ropey = { version = "1.4.1", default-features = false }
tui = "0.17.0"
