[package]
name = "indigo-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
camino = "1.1.6"
fancy-regex = "0.11.0"
ropey = { version = "1.6.1", default-features = false, features = ["simd"] }

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
