[package]
name = "indigo-ui"
edition = "2024"

[dependencies]
ratatui = { workspace = true }
taffy = { version = "0.8.1", default-features = false, features = ["std", "flexbox"] }

[lints]
workspace = true
