[package]
name = "indigo-kernel"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
ropey = { workspace = true }
unicode-segmentation = { workspace = true }

[dev-dependencies]
divan = { workspace = true }
hegeltest = { workspace = true }

[lints]
workspace = true

[[bench]]
name = "edit"
harness = false
