[package]
name = "indigo-kernel"
license = "MPL-2.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
imbl = "7.0.1"
ropey = { workspace = true }
unicode-segmentation = { workspace = true }

[dev-dependencies]
crop = { version = "0.4.3", features = ["graphemes"] }
hegeltest = { workspace = true }

[lints]
workspace = true
