[package]
name = "indigo-kernel"
license = "MPL-2.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
imbl = { workspace = true }
ropey = { workspace = true }
unicode-segmentation = { workspace = true }

[dev-dependencies]
crop = { workspace = true }
hegeltest = { workspace = true }
hegeltest-c = { workspace = true } # TODO: upstream bug workaround :(

[lints]
workspace = true
