[package]
name = "indigo-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
camino = { workspace = true }
clap = { workspace = true }
crossterm = { workspace = true }
indigo-core = { workspace = true }
ratatui = { workspace = true }

[lints]
workspace = true
