[package]
name = "indigo-bevy"
edition = "2024"

[dependencies]
bevy = { version = "0.16.0", default-features = false }
clap = { workspace = true, features = ["derive"] }
ratatui = { workspace = true }

[lints]
workspace = true
