[package]
name = "indigo_core"
version = "0.1.0"
authors = ["Evan Relf <evan@evanrelf.com>"]
license = "ISC"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
camino = "1.0.7"
generational-arena = "0.2.8"
regex = "1.5.5"
ropey = { version = "1.4.1", default-features = false }
