[package]
name = "indigo_core"
version = "0.1.0"
authors = ["Evan Relf <evan@evanrelf.com>"]
license = "ISC"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
bitflags = "1.3.2"
camino = "1.0.8"
downcast-rs = "1.2.0"
generational-arena = "0.2.8"
regex = "1.5.5"
ropey = { version = "1.4.1", default-features = false }
tracing = "0.1.34"
