[package]
name = "indigo_tui"
version = "0.1.0"
authors = ["Evan Relf <evan@evanrelf.com>"]
license = "ISC"
edition = "2021"
default-run = "indigo_tui"

[dependencies]
crossterm = "0.22.1"
indigo_core = { path = "../indigo_core" }
tui = "0.17.0"
