[package]
name = "indigo-core"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
flagset = { workspace = true }
itertools = { workspace = true }
ropey = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
unicode-segmentation = { workspace = true }
unicode-width = { workspace = true }
winnow = { workspace = true }

[dev-dependencies]
arbtest = { workspace = true }

[lints]
workspace = true
