[package]
name = "indigo-core"
edition = "2024"

[dependencies]
flagset = { workspace = true }
ropey = { workspace = true }
thiserror = { workspace = true }
unicode-segmentation = { workspace = true }
unicode-width = { workspace = true }
winnow = { workspace = true }

[dev-dependencies]
arbitrary = { workspace = true }
arbtest = { workspace = true }

[lints]
workspace = true
