[package]
name = "indigo-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
camino = { workspace = true }
flagset = { workspace = true }
icu_properties = { workspace = true }
ropey = { workspace = true }
unicode-segmentation = { workspace = true }
unicode-width = { workspace = true }
winnow = { workspace = true }

[lints]
workspace = true
