[package]
name = "indigo-core"
edition = "2024"

[features]
coz = ["dep:coz"]

[dependencies]
anyhow = { workspace = true }
coz = { workspace = true, optional = true }
flagset = { workspace = true }
itertools = { workspace = true }
ropey = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
unicode-segmentation = { workspace = true }
unicode-width = { workspace = true }
winnow = { workspace = true }

[dev-dependencies]
arbitrary = { workspace = true }
arbtest = { workspace = true }

[lints]
workspace = true
