[package]
name = "indigo-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
camino = { workspace = true }
clap = { workspace = true }
crossterm = { workspace = true }
ratatui = { workspace = true }
ropey = { workspace = true }
unicode-segmentation = { workspace = true }
unicode-width = { workspace = true }

[lints]
workspace = true
